server:
  port: 9900
spring:
  application:
    name: server-zipkin
  security:
    user:
      name: root
      password: root

eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:7900/eureka/
management:
  metrics:
    web:
      server:
        auto-time-requests: false

