server:
  port: 9110

spring:
  application:
    name: zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/
    enabled: true
  instance:
    hostname: localhost
    instance-id: zuul-9110


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      ##默认是never
      show-details: ALWAYS
      enabled: true
    routes:
      enabled: true


datasource:
  #配置当前使用的数据源的操作类型
  type: com.alibaba.druid.pool.DruidDataSource
  #配置MySQL的驱动程序类
  driver-class-name: com.mysql.cj.jdbc.Driver
  #数据库连接地址
  url: jdbc:mysql://localhost:3306/demo?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  #数据库连接用户名
  username: root
  #数据库连接密码
  password: root
  #进行数据库连接池的配置
  dbcp2:
    #初始化提供的连接数
    initial-size: 5
    #数据库连接池的最小维持连接数
    min-idle: 5
    #最大的连接数
    max-total: 5
    #等待连接获取的最大超时时间
    max-wait-millis: 200
    validation-query: SELECT 1
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false