#应用名称及验证账号
spring:
  application:
    name: eureka
  security:
    user:
      name: root
      password: root
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  server:
    #关闭自我保护
    enable-self-preservation: false
    #清理间隔时间
    eviction-interval-timer-in-ms: 5000
    peer-node-read-timeout-ms: 1000
logging:
  level:
    root: info
---
spring:
  profiles: 7900
server:
  port: 7900
eureka:
  client:
    instance:
      hostname: localhost
      instance-id: eureka1-7900
    service-url:
      defaultZone: http://root:root@localhost:7900/eureka/
      #defaultZone: http://root:root@localhost:7901/eureka/
---
spring:
  profiles: 7901
server:
  port: 7901
eureka:
  client:
    instance:
      hostname: localhost
      instance-id: eureka2
    service-url:
      #defaultZone: http://eureka1:7900/eureka/
      defaultZone: http://root:root@localhost:7900/eureka/
